// <auto-generated />
namespace AMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTabelsUserJob_JobMenu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTabelsUserJob_JobMenu));
        
        string IMigrationMetadata.Id
        {
            get { return "201805210539215_AddTabelsUserJob_JobMenu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
